apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    app: curl
spec:
  containers:
    - name: curl
      image: curlimages/curl
      command: ["/bin/sh"]
      args: ["-c", "curl http://10.244.0.108:8080; sleep 300"] #instead of 10.244.0.108 use you ip address of your nginx pod
