# this deployment create three instance of my node application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-nginx-app-deployment
  labels:
    app: learn-nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: learn-nginx-app
  template:
    metadata:
      labels:
        app: learn-nginx-app
    spec:
      containers:
      - name: learn-nginx-app
        image: nafaebm/publicimages:learn-nginx-app
        ports:
        - containerPort: 3000
