name: Build and Push Docker Image

on:
  push:
    branches:
      - master # This will trigger the workflow on changes to the 'master' branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (enables advanced Docker features)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Cache Docker layers to speed up the builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Log in to Docker Hub using GitHub OAuth authentication
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Add your Docker Hub username here
          password: ${{ secrets.DOCKER_PASSWORD }} # Add your Docker Hub password or PAT here

      # Step 5: Remove existing Docker image with the same tag from Docker Hub
      - name: Remove existing Docker image from Docker Hub
        run: |
          # Get the image digest from Docker Hub
          IMAGE_DIGEST=$(curl -s -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}https://hub.docker.com/v2/repositories/nafaebm/testdocker/tags/learn-nginx-app" | jq -r '.images[0].digest')
    
          # Check if the image digest is not empty
          if [ -n "$IMAGE_DIGEST" ]; then
            echo "Image found with digest $IMAGE_DIGEST, removing..."
            # Delete the image using Docker Hub's API
            curl -X DELETE -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}https://hub.docker.com/v2/repositories/nafaebm/testdocker/manifests/$IMAGE_DIGEST"
          else
            echo "Image not found on Docker Hub, skipping removal."
          fi


      # Step 6: Build Docker image
      #- name: Build Docker image
       # run: |
        #  docker build -t nafaebm/testdocker:learn-nginx-app .

      # Step 7: Push the Docker image to Docker Hub
      #- name: Push Docker image
       # run: |
        #  docker push nafaebm/testdocker:learn-nginx-app
